import { ThemeDefinition, AnimationDefinition } from '../types'

export const OCCASIONS = [
  'Birthday',
  'Anniversary',
  'Valentine’s Day',
  'Graduation',
  'New Year',
  'Wedding',
  'Congratulations',
  'Thank You',
  'Holiday & Festivity',
  'Diwali',
  'Christmas',
  'Eid Mubarak',
  'Mother’s Day',
  'Father’s Day',
  'Baby Shower',
  'Get Well Soon',
  'Farewell & Good Luck',
  'Housewarming',
  'Thinking of You',
  'Friendship Day',
  'Custom Wish',
]

export const THEMES: ThemeDefinition[] = [
  {
    id: 'magical-starlight',
    name: 'Magical Starlight',
    description: 'Deep cosmic violet, glowing star dust, and ethereal aura.',
    previewGradient: 'linear-gradient(135deg, #1b0a2a 0%, #2e1065 50%, #4c1d95 100%)',
    accentColor: '#c084fc',
    badge: 'Popular',
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    description: 'Warm amber, golden hour radiance, and soothing rose tones.',
    previewGradient: 'linear-gradient(135deg, #450a0a 0%, #7c2d12 50%, #f97316 100%)',
    accentColor: '#fb923c',
    badge: 'Warm',
  },
  {
    id: 'neon-cyberpunk',
    name: 'Neon Cyberpunk',
    description: 'Electric magenta, neon cyan flares, and dark futuristic pulse.',
    previewGradient: 'linear-gradient(135deg, #09090b 0%, #0369a1 50%, #d946ef 100%)',
    accentColor: '#38bdf8',
    badge: 'Vibrant',
  },
  {
    id: 'romantic-blossom',
    name: 'Romantic Blossom',
    description: 'Soft rose petals, delicate blush quartz, and warm elegance.',
    previewGradient: 'linear-gradient(135deg, #3b0764 0%, #831843 50%, #f43f5e 100%)',
    accentColor: '#fb7185',
    badge: 'Love',
  },
  {
    id: 'golden-elegance',
    name: 'Golden Elegance',
    description: 'Midnight obsidian, brushed gold luxury, and champagne sparkle.',
    previewGradient: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #ca8a04 100%)',
    accentColor: '#facc15',
    badge: 'Luxury',
  },
  {
    id: 'celestial-dream',
    name: 'Celestial Dream',
    description: 'Deep abyss teal, emerald nebula clouds, and shimmering auroras.',
    previewGradient: 'linear-gradient(135deg, #022c22 0%, #064e3b 50%, #0d9488 100%)',
    accentColor: '#2dd4bf',
    badge: 'Dreamy',
  },
  {
    id: 'aurora-borealis',
    name: 'Aurora Borealis',
    description: 'Arctic midnight indigo, dancing polar emeralds, and cyan luminescence.',
    previewGradient: 'linear-gradient(135deg, #0b0f2b 0%, #064e3b 50%, #06b6d4 100%)',
    accentColor: '#22d3ee',
    badge: 'Mystic',
  },
  {
    id: 'cherry-blossom',
    name: 'Sakura Petals',
    description: 'Japanese cherry blossom pink, delicate floral breeze, and spring pastel.',
    previewGradient: 'linear-gradient(135deg, #2d0b1e 0%, #701a75 50%, #f472b6 100%)',
    accentColor: '#f472b6',
    badge: 'Floral',
  },
  {
    id: 'midnight-velvet',
    name: 'Midnight Velvet',
    description: 'Royal indigo depths, purple orchid glow, and star-studded mystery.',
    previewGradient: 'linear-gradient(135deg, #090a1a 0%, #1e1b4b 50%, #818cf8 100%)',
    accentColor: '#818cf8',
    badge: 'Royal',
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    description: 'Deep aquamarine, cerulean tides, and radiant tropical coral glow.',
    previewGradient: 'linear-gradient(135deg, #082f49 0%, #0284c7 50%, #38bdf8 100%)',
    accentColor: '#38bdf8',
    badge: 'Fresh',
  },
  {
    id: 'autumn-whisper',
    name: 'Autumn Whisper',
    description: 'Cozy spiced maple, burnt sienna, and warm harvest candlelight.',
    previewGradient: 'linear-gradient(135deg, #2d1305 0%, #78350f 50%, #d97706 100%)',
    accentColor: '#fbbf24',
    badge: 'Cozy',
  },
  {
    id: 'ruby-royalty',
    name: 'Ruby Royalty',
    description: 'Deep crimson velvet, regal garnet aura, and antique gold accents.',
    previewGradient: 'linear-gradient(135deg, #450a0a 0%, #881337 50%, #e11d48 100%)',
    accentColor: '#f43f5e',
    badge: 'Regal',
  },
  {
    id: 'lavender-haze',
    name: 'Lavender Haze',
    description: 'Serene pastel periwinkle, dreamy lavender mist, and cloud softness.',
    previewGradient: 'linear-gradient(135deg, #181829 0%, #4c1d95 50%, #a78bfa 100%)',
    accentColor: '#a78bfa',
    badge: 'Peaceful',
  },
  {
    id: 'emerald-enchantment',
    name: 'Emerald Garden',
    description: 'Enchanted forest moss, mythical jade gleams, and golden dew drops.',
    previewGradient: 'linear-gradient(135deg, #052e16 0%, #14532d 50%, #10b981 100%)',
    accentColor: '#34d399',
    badge: 'Enchanted',
  },
]

export const ANIMATIONS: AnimationDefinition[] = [
  {
    id: 'floating-sparkles',
    name: 'Floating Sparkles',
    description: 'Glimmering star particles drifting across the background.',
    icon: '✨',
  },
  {
    id: 'confetti-cascade',
    name: 'Confetti Cascade',
    description: 'Joyful celebration confetti falling across the screen.',
    icon: '🎉',
  },
  {
    id: 'gentle-hearts',
    name: 'Gentle Hearts',
    description: 'Soft floating romantic hearts rising gracefully.',
    icon: '💖',
  },
  {
    id: 'cosmic-fireworks',
    name: 'Cosmic Fireworks',
    description: 'Bursting light rays and glowing celestial fireworks.',
    icon: '🎆',
  },
  {
    id: 'floating-balloons',
    name: 'Celebration Balloons',
    description: 'Colorful festive balloons swaying in the breeze.',
    icon: '🎈',
  },
  {
    id: 'pulsing-glow',
    name: 'Pulsing Glow',
    description: 'Hypnotic ambient radial light pulses and color shifts.',
    icon: '🌟',
  },
  {
    id: 'shooting-stars',
    name: 'Shooting Stars',
    description: 'Brilliant meteors streaking across a starry night.',
    icon: '🌠',
  },
  {
    id: 'cherry-petals',
    name: 'Sakura Petals',
    description: 'Delicate floral blossom petals fluttering in the wind.',
    icon: '🌸',
  },
  {
    id: 'floating-lanterns',
    name: 'Sky Lanterns',
    description: 'Luminous festival lanterns rising gently into the sky.',
    icon: '🏮',
  },
  {
    id: 'snowfall-magic',
    name: 'Snowfall Magic',
    description: 'Whimsical crystal snowflakes falling softly.',
    icon: '❄️',
  },
  {
    id: 'firefly-dance',
    name: 'Dancing Fireflies',
    description: 'Golden enchanted fireflies floating in organic harmony.',
    icon: '💡',
  },
  {
    id: 'champagne-bubbles',
    name: 'Golden Bubbles',
    description: 'Effervescent sparkling bubbles rising in celebratory cheer.',
    icon: '🥂',
  },
]
